name: "Setup voyager-vpm"
description: "Install voyager-vpm from the official release installer with SHA256 verification"

inputs:
  installer-url:
    description: "URL of voyager installer script"
    required: false
    default: "https://github.com/Limitex/voyager-vpm/releases/download/v0.2.0/voyager-installer.sh"
  installer-sha256:
    description: "Expected SHA256 of voyager installer script"
    required: false
    default: "f47714955d147368e4417bd202cfe7767c93177b106e7354a7d92e6fccb76fea"

runs:
  using: "composite"
  steps:
    - name: Install voyager-vpm
      shell: bash
      run: |
        set -euo pipefail
        installer="$RUNNER_TEMP/voyager-installer.sh"
        curl --proto '=https' --tlsv1.2 -fLsS "${{ inputs.installer-url }}" -o "$installer"
        actual_sha256="$(sha256sum "$installer" | awk '{print $1}')"
        if [[ "$actual_sha256" != "${{ inputs.installer-sha256 }}" ]]; then
          echo "Installer checksum mismatch: expected ${{ inputs.installer-sha256 }}, got $actual_sha256" >&2
          exit 1
        fi
        bash "$installer"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
