name: 'Create Manifest Pull Request'

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  PACKAGE_TITLE: "Limitex Packages"
  PACKAGE_AUTHOR: "Limitex"
  PACKAGE_ID: "dev.limitex"
  PACKAGE_URL: "https://vpm.limitex.dev/index.json"
  REPOSITORIES: "Limitex/mono-ui"
  OUTPUT: ${{ github.workspace }}/dist
  FILENAME: index.json
  MINIFIED: true

jobs:
  create-pr:
    name: Create Manifest Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create repository manifest
        uses: Limitex/vrchat-package-lister@b1e167abe03b2a70161b2caec1cfe7b1ac477f70
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-title: ${{ env.PACKAGE_TITLE }}
          package-author: ${{ env.PACKAGE_AUTHOR }}
          package-id: ${{ env.PACKAGE_ID }}
          package-url: ${{ env.PACKAGE_URL }}
          repositories: ${{ env.REPOSITORIES }}
          output: ${{ env.OUTPUT }}
          filename: ${{ env.FILENAME }}
          minified: ${{ env.MINIFIED }}

      - name: Create Pull Request if changes exist
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Update package manifest'
          title: '📝 Update Package Manifest'
          body: |
            Package manifest has been updated by an automated process.
            Please review the changes and merge to deploy.
          branch: 'update-manifest'
          delete-branch: true